In [2]:
from e3nn.o3 import Irreps, spherical_harmonics
import torch
import numpy as np

In [10]:
edge_vecs = torch.randn(5, 3)  # 5 random edge vectors
l_max = 2
irreps_sh = Irreps.spherical_harmonics(l_max)
Y = spherical_harmonics(irreps_sh, edge_vecs, normalize=True, normalization='component')
Y

tensor([[ 1.0000, -0.3719, -0.6504, -1.5616,  0.7497,  0.3123, -0.6450,  1.3113,
          1.4849],
        [ 1.0000,  1.2000, -1.1085,  0.5755,  0.8916, -1.7173,  0.2557, -0.8236,
         -0.7157],
        [ 1.0000,  0.6905, -0.8562, -1.3379, -1.1927, -0.7633, -0.2984,  1.4789,
          0.8476],
        [ 1.0000,  0.7254, -1.5410,  0.3148,  0.2948, -1.4432,  1.5369, -0.6262,
         -0.2757],
        [ 1.0000, -1.2859, -0.0655,  1.1585, -1.9233,  0.1087, -1.1132, -0.0979,
         -0.2009]])

In [11]:
edge_vecs

tensor([[-0.2806, -0.4908, -1.1784],
        [ 1.7242, -1.5926,  0.8269],
        [ 1.2776, -1.5842, -2.4753],
        [ 0.2846, -0.6045,  0.1235],
        [-1.1959, -0.0609,  1.0775]])

In [12]:
edge_vecs_norm = edge_vecs / edge_vecs.norm(dim=-1, keepdim=True)
edge_vecs_norm

tensor([[-0.2147, -0.3755, -0.9016],
        [ 0.6928, -0.6400,  0.3323],
        [ 0.3987, -0.4943, -0.7724],
        [ 0.4188, -0.8897,  0.1817],
        [-0.7424, -0.0378,  0.6689]])

In [13]:
Y_norm = spherical_harmonics(irreps_sh, edge_vecs_norm, normalize=True, normalization='component')
Y_norm

tensor([[ 1.0000, -0.3719, -0.6504, -1.5616,  0.7497,  0.3123, -0.6450,  1.3113,
          1.4849],
        [ 1.0000,  1.2000, -1.1085,  0.5755,  0.8916, -1.7173,  0.2557, -0.8236,
         -0.7157],
        [ 1.0000,  0.6905, -0.8562, -1.3379, -1.1927, -0.7633, -0.2984,  1.4789,
          0.8476],
        [ 1.0000,  0.7254, -1.5410,  0.3148,  0.2948, -1.4432,  1.5369, -0.6262,
         -0.2757],
        [ 1.0000, -1.2859, -0.0655,  1.1585, -1.9233,  0.1087, -1.1132, -0.0979,
         -0.2009]])